#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)
ITEM_MARGIN=5
LABEL_FONT="$FONT:Medium:12.0"

# Bar
BAR_HEIGHT=32
BAR_COLOR=0xAA36485E
BAR_BORDER_COLOR="$ORANGE"
BAR_BORDER_WIDTH=0
BAR_PADDING=10

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=45
  color=$TRANSPARENT
  border_width=0
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=botten
  sticky=on
  # y_offset=-5
  # margin=10
  topmost=window
  corner_radius=5

  y_offset=0
  height="$BAR_HEIGHT"
  # border_width="$BAR_BORDER_WIDTH"
  margin=-"$BAR_BORDER_WIDTH"  # NOTE: same as the minus `border_width` to remove the borders on both sides
  corner_radius=0

  padding_left="$BAR_PADDING"
  padding_right="$BAR_PADDING"

  # topmost=off  # set to `window` to avoid sketchybar being covered by windows

  notch_width=350

  font_smoothing=off
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:15.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# -----------------------------------
# -------- Custom Events
# -----------------------------------
sketchybar \
  --add event bluetooth_on "IOBluetoothHostControllerPoweredOnNotification"   \
  --add event bluetooth_off "IOBluetoothHostControllerPoweredOffNotification" \
  \
  --add event yabai_loaded              \
  --add event yabai_window_created      \
  --add event yabai_window_moved        \
  --add event yabai_window_focused      \
  --add event yabai_window_resized      \
  --add event yabai_application_visible \
  --add event skhd_space_type_changed   \
  --add event skhd_window_type_changed

# Left
# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/yabai.sh"

# Center
source "$ITEM_DIR/spotify.sh"
# source "$ITEM_DIR/media.sh"

# Right
# source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/github.sh"
# source "$ITEM_DIR/wifi.sh"
# source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/cpu.sh"
# source "$ITEM_DIR/svim.sh"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
